# Generated by Django 2.0.5 on 2018-09-03 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('category', models.CharField(choices=[('生活用品', '生活用品'), ('服饰', '服饰'), ('餐饮', '餐饮'), ('孩子', '孩子'), ('装修', '装修'), ('其他', '其他'), ('收入', '收入')], max_length=30)),
                ('money_type', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('type', models.IntegerField(default=0)),
                ('chart_type', models.IntegerField(default=0)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedEnvelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(blank=True, max_length=10, null=True)),
                ('money_type', models.IntegerField(default=0)),
                ('money_from', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.PositiveSmallIntegerField(default=2)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('user_type', models.PositiveSmallIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('whats_up', models.CharField(blank=True, max_length=200, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, max_length=500, null=True)),
                ('highlighted', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_email_activate', models.BooleanField(default=False)),
                ('is_phone_activate', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='redenvelope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaer.User'),
        ),
        migrations.AddField(
            model_name='iaer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaer.User'),
        ),
    ]
