# Generated by Django 2.0.5 on 2018-11-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaer',
            name='category',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
