# Generated by Django 2.0.2 on 2019-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=20)),
                ('version_code', models.PositiveIntegerField()),
                ('apk', models.FileField(upload_to='apks/')),
                ('category', models.PositiveIntegerField(choices=[(1, 'Release'), (2, 'Debug'), (3, 'Test')], default=1)),
                ('comment', models.TextField(max_length=1024)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
