# Generated by Django 2.0.5 on 2018-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0002_auto_20181113_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaer',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
