# Generated by Django 2.0.2 on 2019-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='apk',
            field=models.FileField(blank=True, null=True, upload_to='apks/'),
        ),
    ]
