# Generated by Django 2.0.5 on 2018-11-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0003_auto_20181114_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaer',
            name='category',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='fund',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iaer.Fund'),
        ),
    ]
