# Generated by Django 2.0.5 on 2018-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0007_auto_20181114_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='iaer',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='redenvelope',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='iaer',
            name='category',
            field=models.CharField(choices=[('饮食', '饮食'), ('服饰美容', '服饰美容'), ('生活日用', '生活日用'), ('住房缴费', '住房缴费'), ('交通出行', '交通出行'), ('通讯物流', '通讯物流'), ('文教娱乐', '文教娱乐'), ('健康保险', '健康保险'), ('人情往来', '人情往来'), ('装修', '装修'), ('小孩奶粉', '小孩奶粉'), ('小孩尿布', '小孩尿布'), ('小孩玩具', '小孩玩具'), ('小孩健康', '小孩健康'), ('小孩零食', '小孩零食'), ('小孩服饰', '小孩服饰'), ('小孩文具', '小孩文具'), ('小孩生活用品', '小孩生活用品'), ('小孩其他', '小孩其他'), ('其他消费', '其他消费'), ('收入', '收入')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='iaer',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
