# Generated by Django 2.0.5 on 2018-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0009_auto_20181220_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='monthly_fund',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='yearly_fund',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
