# Generated by Django 2.0.5 on 2018-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0010_auto_20181226_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='yearly_fund',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
