# Generated by Django 2.0.5 on 2019-11-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0011_auto_20181227_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
