# Generated by Django 2.0.5 on 2019-11-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaer', '0012_iaer_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iaer',
            options={'ordering': ['-date']},
        ),
    ]
