# Generated by Django 2.0.2 on 2020-07-17 17:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('date_format', models.CharField(choices=[('0', '不显示'), ('1', '显示日期'), ('2', '显示年龄'), ('3', '显示日期和年龄')], default='0', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exif_image_width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='image width')),
                ('exif_image_height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='image height')),
                ('exif_make', models.CharField(blank=True, max_length=50, null=True, verbose_name='make')),
                ('exif_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='model')),
                ('exif_lens_make', models.CharField(blank=True, max_length=50, null=True, verbose_name='lens make')),
                ('exif_lens_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='lens model')),
                ('exif_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='exif version')),
                ('exif_subject_location', models.CharField(blank=True, max_length=30, null=True, verbose_name='subject location')),
                ('exif_datetime', models.DateField(blank=True, null=True, verbose_name='datetime')),
                ('exif_datetime_original', models.DateField(blank=True, null=True, verbose_name='datetime original')),
                ('exif_datetime_digitized', models.DateField(blank=True, null=True, verbose_name='datetime digitized')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='size')),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='label'), blank=True, null=True, size=None)),
                ('sub_dir', models.CharField(max_length=10, verbose_name='sub_dir')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('sha1sum', models.CharField(max_length=50, verbose_name='sha1sum')),
                ('category', models.PositiveSmallIntegerField(default=0, verbose_name='category')),
                ('version', models.PositiveSmallIntegerField(default=0, verbose_name='version')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('galleries', models.ManyToManyField(blank=True, to='photo.Gallery')),
            ],
            options={
                'ordering': ['exif_datetime_original'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.PositiveSmallIntegerField(default=2)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('date_format', models.CharField(choices=[('0', '不显示'), ('1', '显示日期'), ('2', '显示年龄'), ('3', '显示日期和年龄')], default='0', max_length=50)),
                ('user_type', models.PositiveSmallIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('whats_up', models.CharField(blank=True, max_length=200, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, max_length=500, null=True)),
                ('highlighted', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_email_activate', models.BooleanField(default=False)),
                ('is_phone_activate', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo.User', verbose_name='user'),
        ),
    ]
