# Generated by Django 2.0.5 on 2018-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('date_format', models.CharField(choices=[('0', '不显示'), ('1', '显示日期'), ('2', '显示年龄'), ('3', '显示日期和年龄')], default='0', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['exif_datetime_original']},
        ),
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(choices=[('0', '不显示'), ('1', '显示日期'), ('2', '显示年龄'), ('3', '显示日期和年龄')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='photo.Gallery'),
        ),
    ]
