# Generated by Django 2.0.2 on 2020-07-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=0)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_buy_price', models.FloatField()),
                ('m_buy_price', models.FloatField()),
                ('f_sell_price', models.FloatField()),
                ('m_sell_price', models.FloatField()),
                ('bank_conversion_price', models.FloatField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='tools.Currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='tools.Currency')),
            ],
        ),
    ]
