# Generated by Django 2.0.2 on 2020-07-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='exchagne',
            new_name='exchange',
        ),
    ]
