# Generated by Django 2.0.2 on 2020-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20200717_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='transaction_unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
